### ISSUE TITLE
Scavenger Hunt: Figure out how the map features get styled differently when they are hovered over

### ISSUE THREAD

**Issue by Bonkles** [MLH-Fellowship/RapiD#1]
This task will get you famiilar with eventing and .css styling within RapiD.

You'll notice that as you scroll around the map, features are styled differently when they are hovered over.

Can you determine how this works?

Pop open the browser dev tools, look at the 'Elements' tab, and search (cmd or ctrl-F) for .layer.layer-data . This is a .css selector that should take you to the following element:

![image](https://user-images.githubusercontent.com/1887955/154742513-74be6b22-3978-418c-bd29-3fdb0a89ed34.png)

Within here, you will find ALL of the markup that gets rendered to the DOM in order to draw the map. You don't have to know how EVERYTHING works in here, but try to find the data layer that governs rapid's data- it's in its own section of the DOM underneath here. Then try hovering over a rapid feature and see what happens to it in the DOM.

**Comment by hieule21** [comment]
I looked mainly into how fb and microsoft features got rendered in the file rapid_features.js. The main workflow is understandable. There're some helpers functions on the way and I only try to understand what they do and what they output. I would want to catch up with functional programming style as well if I were to implement new features.
