### ISSUE TITLE
Scavenger Hunt: Using the network tab in the browser devtools, try to find how the data we get from mapillary's backend services are structured/formatted

### ISSUE THREAD

**Issue by Bonkles** [MLH-Fellowship/RapiD#2]
Part of understanding what gets rendered to the map is understanding where that data comes from, and how it is structured.

To accomplish this task, you will need to:

Find an area of the map that contains mapillary objects and traffic signs.
Enable those layers in the map using the 'map data' option in the right-hand sidebar, then 'photo overlays->mapillary->map features' and 'map signs'.
Screenshot:

![image](https://user-images.githubusercontent.com/1887955/154742719-eba13746-5c95-4ec5-8f64-c4f3f89d62ba.png)
You can head to detroit, MI to see tons of examples of mapillary data.

To get to detroit, you can use the feature search bar in the upper-left of the rapid UI:
![image](https://user-images.githubusercontent.com/1887955/154742764-2445e0cd-64de-4ce9-adb7-5679ea67384d.png)

**Comment by MahmoudMuhammedAli** [comment]
- data comes mainly from: `https://graph.mapillary.com` and `https://mapwith.ai/rapid`
-  request: `https://graph.mapillary.com//1142183016308648/detections?access_token=MLY|3376030635833192|f13ab0bdf6b2f7b99e0d8bd5868e1d88&fields=id,value,image`
`# example response for tiles
{
   "data": [
      {
         "url": "https://scontent.fcai19-4.fna.fbcdn.net/m1/v/t6/An_Hsr8ZDUb6a_vumArxv4_NRTndlW5UJl_LKOiDuU44yFU7zUzjRfaG0zaF1_IlMey5BvWT4GApwpRlXjtLiFWkgXzemSdsAHnbN5DB0IYAOUI_om3LysgtS-xFRvZd1V1OwIU0a8z2r4DL5BQs0kk?stp=c0.0.4096.4000a_s1024x1024&ccb=10-5&oh=00_AT9kRpUXHlqTQhXsSRWoFphUNem7tsRmYywKdldcc96log&oe=62146099&_nc_sid=122ab1",
         "z": 11,
         "x": 0,
         "y": 0
      },
      {
         "url": "https://scontent.fcai19-4.fna.fbcdn.net/m1/v/t6/An_Hsr8ZDUb6a_vumArxv4_NRTndlW5UJl_LKOiDuU44yFU7zUzjRfaG0zaF1_IlMey5BvWT4GApwpRlXjtLiFWkgXzemSdsAHnbN5DB0IYAOUI_om3LysgtS-xFRvZd1V1OwIU0a8z2r4DL5BQs0kk?stp=c4096.0.3904.4000a_s1024x1024&ccb=10-5&oh=00_AT8p-w_iDpj6G_sQle3MBtI3UI4Xx9ay2odDR7tuAwD6Tg&oe=62146099&_nc_sid=122ab1",
         "z": 11,
         "x": 1,
         "y": 0
      }
   ]
}`


`# example response for the a street light
   {
         "id": "147888333990126",
         "image": {
            "geometry": {
               "type": "Point",
               "coordinates": [
                  -83.047415359139,
                  42.363216409778
               ]
            },
            "id": "147428514036108"
         },
         "geometry": "Gi14AgoGbXB5LW9yKIAgEh4IARgDIhgJRuYYSgYCBAYACAEEGQgFBwAJAgMMBQ8=",
         "value": "object--street-light"
      },`
