### ISSUE TITLE
Create a new mapillary service call to get ONLY streetlights, benches, bike racks, and fire hydrants.

### ISSUE THREAD

**Issue by Bonkles** [MLH-Fellowship/RapiD#3]
Mapillary objects are fetched via GraphQL request to the mapillary backend. 

RapiD already knows how to fetch objects from mapillary in the following
code: `modules/services/mapillary.js` in the `mapFeatures()` method. 

This task requires you to figure out how to create a graphql request to the mapillary backend that only queries for the points that we need.  

UPDATE: Here's some more information about the backend API and how you can request just these features. 

Mapillary dev documentation: 
https://www.mapillary.com/developer/api-documentation#map-feature

To obtain the object types we're interested in, supply the `object_values=VALUENAMES` and the valuenames can be a comma-separated list of values. The object values for streetlights, benches, bike racks, and fire hydrants are as follows: 

```
object--street-light
object--bench
object--bike-rack
object--fire-hydrant
```

So, supplying `values=object--street-light,object--bench,object--bike-rack,object--fire-hydrant` should do the trick.

**Comment by hieule21** [comment]
For now, we filter directly on the return of mapFeatures() method to get the data we need. We're waiting for Chris to see if there's a better way to do this.
