### ISSUE TITLE
Create a new renderer for the new mapillary objects layer. 

### ISSUE THREAD

**Issue by Bonkles** [MLH-Fellowship/RapiD#4]
(This work is contingent on issue #3 being completed)

We already know how to render ALL the map features we get from the mapillary backend: There is already a complete renderer in `modules/svg/mapillary_map_features.js`. We need a slightly different renderer, but we can start by copying this one and renaming it.

Copy the mapillary map features renderer, and call it something like 'mapillary_rapid_features.js'. 

For now, stub out the 'click' method- we just want to get things rendering, we can add interactivity later. 

The mapillary service should already have been upgraded in Issue #3 to load JUST the features we want for this new workflow.  Check to see what the new loading method is called, and replace the line that calls `service.mapFeatures()` with the new one you created in #3.

Next up- to add the interactivity in a menu to show and hide this new layer!

**Comment by hieule21** [comment]
Created an exact copy and swapped out the mapFeatures() method. Ready for issue #5.
